services:
  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    ports:
      - "${MONGODB_LOCAL_PORT}:${MONGODB_DOCKER_PORT}"
    volumes:
      - ./mongodb:/data/db

  redis:
    image: redis:latest
    ports:
      - "${REDIS_LOCAL_PORT}:${REDIS_DOCKER_PORT}"

  server:
    depends_on:
      - mongo
      - redis
    environment:
      - MONGODB_USER=${MONGODB_USER}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_DATABASE=${MONGODB_DATABASE}
      - MONGODB_HOST=${MONGODB_HOST}
      - MONGODB_DOCKER_PORT=${MONGODB_DOCKER_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_DOCKER_PORT=${REDIS_DOCKER_PORT}
      - NODE_SERVER_HOST=${NODE_SERVER_HOST}
      - NODE_SERVER_LOCAL_PORT=${NODE_SERVER_LOCAL_PORT}
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/usr/src/server
      - /usr/src/server/node_modules
    deploy:
      mode: replicated
      replicas: 3

  nginx:
    depends_on:
      - server
    environment:
      - NODE_SERVER_LOCAL_PORT=${NODE_SERVER_LOCAL_PORT}
      - NGINX_DOCKER_PORT=${NGINX_DOCKER_PORT}
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "${NGINX_LOCAL_PORT}:${NGINX_DOCKER_PORT}"